import { RecaptchaEnterpriseServiceClient } from '@google-cloud/recaptcha-enterprise';
import axios from 'axios';
import logger from '../utils/logger.js';

/**
 * Verify a reCAPTCHA Enterprise token.
 * Supports both Google Cloud SDK (Service Account) and REST API (API Key).
 * 
 * @param {string} token - The token generated by the client.
 * @param {string} recaptchaAction - The action name associated with the token.
 * @returns {Promise<number|null>} - The risk score (0.0 to 1.0) or null if invalid.
 */
export async function verifyRecaptchaToken(token, recaptchaAction = "LOGIN") {
    const projectID = process.env.FIREBASE_PROJECT_ID || "tagt-auth-a9c79";
    const recaptchaKey = process.env.RECAPTCHA_SITE_KEY || "6LcYdYIsAAAAALs9O0fknr8dlztXd6NDHYiE0mYd";
    const apiKey = process.env.RECAPTCHA_API_KEY;

    if (!token) {
        logger.warn('reCAPTCHA verification skipped: No token provided');
        return null;
    }

    // --- Method 1: REST API with API Key (Simpler setup) ---
    if (apiKey) {
        try {
            const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${projectID}/assessments?key=${apiKey}`;
            const response = await axios.post(url, {
                event: {
                    token: token,
                    siteKey: recaptchaKey,
                    expectedAction: recaptchaAction
                }
            });

            const data = response.data;
            if (!data.tokenProperties?.valid) {
                logger.error(`reCAPTCHA REST failed: ${data.tokenProperties?.invalidReason}`);
                return null;
            }

            const score = data.riskAnalysis?.score;
            logger.info(`reCAPTCHA REST score [${recaptchaAction}]: ${score}`);
            return score;
        } catch (err) {
            logger.error('reCAPTCHA REST API Error', { error: err.message });
            // Fall through to Method 2 or fail gracefully
        }
    }

    // --- Method 2: Google Cloud SDK (Service Account) ---
    try {
        const client = new RecaptchaEnterpriseServiceClient({
            credentials: {
                client_email: process.env.FIREBASE_CLIENT_EMAIL,
                private_key: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
            },
            projectId: projectID,
        });

        const projectPath = client.projectPath(projectID);
        const request = {
            assessment: {
                event: {
                    token: token,
                    siteKey: recaptchaKey,
                },
            },
            parent: projectPath,
        };

        const [response] = await client.createAssessment(request);

        if (!response.tokenProperties) {
            logger.error('reCAPTCHA SDK response missing tokenProperties');
            return 1.0;
        }

        if (!response.tokenProperties.valid) {
            logger.error(`reCAPTCHA SDK failed: ${response.tokenProperties.invalidReason}`);
            return null;
        }

        const score = response.riskAnalysis.score;
        logger.info(`reCAPTCHA SDK score [${recaptchaAction}]: ${score}`);
        return score;

    } catch (err) {
        logger.error('reCAPTCHA SDK Error - falling gracefully with score 1.0', { error: err.message });
        return 1.0;
    }
}
