import { RecaptchaEnterpriseServiceClient } from '@google-cloud/recaptcha-enterprise';
import logger from '../utils/logger.js';

/**
 * Verify a reCAPTCHA Enterprise token by creating an assessment.
 * 
 * @param {string} token - The token generated by the client.
 * @param {string} recaptchaAction - The action name associated with the token.
 * @returns {Promise<number|null>} - The risk score (0.0 to 1.0) or null if invalid.
 */
export async function verifyRecaptchaToken(token, recaptchaAction = "LOGIN") {
    const projectID = process.env.FIREBASE_PROJECT_ID;
    const recaptchaKey = process.env.RECAPTCHA_SITE_KEY || "6LcYdYIsAAAAALs9O0fknr8dlztXd6NDHYiE0mYd";

    if (!token) {
        logger.warn('reCAPTCHA verification skipped: No token provided');
        return null;
    }

    try {
        const client = new RecaptchaEnterpriseServiceClient({
            credentials: {
                client_email: process.env.FIREBASE_CLIENT_EMAIL,
                private_key: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
            },
            projectId: projectID,
        });

        const projectPath = client.projectPath(projectID);

        const request = {
            assessment: {
                event: {
                    token: token,
                    siteKey: recaptchaKey,
                },
            },
            parent: projectPath,
        };

        const [response] = await client.createAssessment(request);

        if (!response.tokenProperties.valid) {
            logger.error(`reCAPTCHA assessment failed: ${response.tokenProperties.invalidReason}`);
            return null;
        }

        if (response.tokenProperties.action === recaptchaAction) {
            const score = response.riskAnalysis.score;
            logger.info(`reCAPTCHA score for action ${recaptchaAction}: ${score}`);

            // Log reasons for low scores if needed
            if (score < 0.5) {
                response.riskAnalysis.reasons.forEach((reason) => {
                    logger.warn(`reCAPTCHA low score reason: ${reason}`);
                });
            }

            return score;
        } else {
            logger.error(`reCAPTCHA action mismatch: expected ${recaptchaAction}, got ${response.tokenProperties.action}`);
            return null;
        }
    } catch (err) {
        logger.error('Error during reCAPTCHA verification', { error: err.message });
        return null;
    }
}
